# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YandexKassa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YandexKassa



  pod 'YandexCheckoutPayments',
      :git => 'https://github.com/DevTchernov/yandex-checkout-payments-swift.git',
      :branch => 'remove-metrica'


end
